### ISSUE TITLE
Relative vs absolute pressure?

### ISSUE THREAD

**Issue by agoode** [Airthings/airthings-ble#31]
**Describe the bug**
Looking at the code (https://github.com/Airthings/airthings-ble/blob/eba0c2b56341eb62fcfdf92c578ba66581fe931b/airthings_ble/parser.py#L140) suggests that the sensor is reporting "relative" pressure. It is then converted into "absolute" pressure here: https://github.com/Airthings/airthings-ble/blob/eba0c2b56341eb62fcfdf92c578ba66581fe931b/airthings_ble/parser.py#L326

I don't think this is correct. According to https://ambientweather.com/faqs/question/view/id/1591/ the raw sensor data is the "absolute" pressure, and the altitude-corrected pressure is the relative one.

If I understand correctly, the sensor is reporting the absolute pressure, and your function is converting it to the relative pressure.

While I've seen some sensors report relative pressure, they report it along with absolute pressure as a different entity. So while it's ok to have both, it's important to report the absolute pressure.

Also: The airthings dashboard reports the absolute pressure.

I would suggest dropping the absolute->relative conversion and report the absolute pressure with the existing entity. If the sensor itself was computing the relative pressure, you could report it but since you're computing it in this code, it doesn't seem necessary. I'm not sure if just changing this is the right thing to do for compatibility reasons, but I'm also not sure of the best way to migrate the use.

**Comment by agoode** [comment]
Thank you!

**Comment by LaStrada** [comment]
Thank you for reporting! 🙏 I'm preparing a release as we speak, but need to do a few changes in the HA integration + some internal testing over the weekend. Will probably not be part of the HA 2024.3.0 release, but hopefully one of the hotfix releases this month.
