### ISSUE TITLE
Add support for Airthings Renew

### ISSUE THREAD

**Issue by mcab** [Airthings/airthings-ble#34]
Hi!

I'm interested in adding support for the [Airthings Renew](https://www.airthings.com/renew).

**Comment by mcab** [comment]
If this is not the right repo, please let me know. If it is, I wish I could have just submitted a PR outright, but I'll need a bit of help on where to look, and how to test things (both BLE and the integration with Home Assistant).

- I've already gotten some Bluetooth output from [Bluetility](https://github.com/jnross/Bluetility) about the device [1].
- I have not registered the device to an Airthings account.
- I am pretty comfortable setting up the testing environment with the [instructions provided](https://github.com/Airthings/airthings-ble/wiki/Testing-with-Home-Assistant).

<details>

<summary>Output from Bluetility [1]</summary>

```
Peripheral: Renew AP-1 didDiscoverCharacteristics: [Model Number String, Manufacturer Name String, System ID, Serial Number String, Firmware Revision String, Hardware Revision String, Software Revision String] for: Device Information 
Peripheral: Renew AP-1 didUpdateValueFor: Model Number String to: 343130
Peripheral: Renew AP-1 didUpdateValueFor: Manufacturer Name String to: 4169727468696E6773204153
Peripheral: Renew AP-1 didUpdateValueFor: System ID to: <system ID>
Peripheral: Renew AP-1 didUpdateValueFor: Serial Number String to: <serial number>
Peripheral: Renew AP-1 didUpdateValueFor: Firmware Revision String to: 482D5749462D312E302E32
Peripheral: Renew AP-1 didUpdateValueFor: Hardware Revision String to: 5245562031
Peripheral: Renew AP-1 didUpdateValueFor: Software Revision String to: 312E302E30
```

```
Peripheral: Renew AP-1 didDiscoverCharacteristics: [B42EB73A-ADE7-11E4-89D3-123B93F75CBA, B42EB9F6-ADE7-11E4-89D3-123B93F75CBA, B42EBC9E-ADE7-11E4-89D3-123B93F75CBA] for: B42EB4A6-ADE7-11E4-89D3-123B93F75CBA
```

</details>

**Comment by LaStrada** [comment]
Congratulations on your new Renew device! 🎉 As you've mentioned, the device does support BLE, but it doesn't provide any sensor data or allow for changing/reading modes over BLE.
