### ISSUE TITLE
Support for View Plus

### ISSUE THREAD

**Issue by criemen** [Airthings/airthings-ble#41]
Hi,

is there any timeline for support of the View Plus device series in homeassistant/`airthings_ble`?
Internally, the Model ID is 2960, but the service UUIDs I'm reading from the device aren't mentioned in the repository here, so creating support for this device probably requires internal access to the specification.

**Comment by LaStrada** [comment]
Hi, and thanks for reaching out! View Plus doesn't support using Bluetooth to read sensor data. You have to use our API (cloud) to fetch data.
