### ISSUE TITLE
Support for View Radon

### ISSUE THREAD

**Issue by leandrotoledo** [Airthings/airthings-ble#43]
Hi Airthings Team,

Thanks for creating this integration! It's a great addition to the Home Assistant ecosystem.

I'm interested in knowing if there are plans to support the [Airthings View Radon](https://www.airthings.com/en/view-radon) device; assuming this device can be queried via Bluetooth - it would be fantastic to have it added to the integration.

If not, providing a clear overview of supported, unsupported, and planned devices as a table in the repository `README.md` would be very helpful for the community. 

Thanks for considering this request!

**Comment by HormCodes** [comment]
Hi @leandrotoledo, thank you for the interest! 🙌 

Unfortunately, this device uses BLE only for onboarding and configuration. It is not possible to use this integration with this device. Thank you also for the feedback regarding README, it will be addressed in #44. 🙏
